### ISSUE TITLE
Búsqueda de información - anteproyecto

### ISSUE THREAD

**Issue by tatipar** [Rysen-Winters/ia-uncuyo-2023#1]
Ver qué se ha hecho al respecto (proyectos similares) y agregar a bibliografía (papers, notebooks, etc)
Dedicar más tiempo a esta búsqueda (cronograma)

**Comment by Rysen-Winters** [comment]
Fixed in last commit

**Comment by Rysen-Winters** [comment]
Related and similar researchs have been added in recent commit
